[package]
name = "condenser-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
anyhow.workspace = true
uuid.workspace = true
directories.workspace = true
tracing.workspace = true
ureq.workspace = true
sevenz-rust2.workspace = true
tar.workspace = true
bzip2.workspace = true

[dev-dependencies]
tempfile = "3"

[lints]
workspace = true
