//! Configuration for the `gbe_fork` emulator, global and per-game.
//!
//! The emulator reads four INI files from its `steam_settings/` folder, and the section
//! prefix identifies the file: `[user::general]` lives in `configs.user.ini`,
//! `[app::dlcs]` in `configs.app.ini`, and so on.
//!
//! Upstream also supports a *global* settings folder (`GSE Saves/settings/`) which the
//! per-game folder overrides. Condenser does not write there: for Windows games that
//! path resolves inside the Wine prefix, and since every game gets its own prefix it
//! would not be global at all. Instead the global layer is kept here, merged with the
//! game's own entries at deploy time, and written to `steam_settings/` — which upstream
//! documents as always winning. The observable precedence is identical, and it works
//! the same for native Linux games.

use crate::error::{Error, Result};
use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::path::Path;

/// Section name -> the key/value pairs it contains.
type SectionMap = BTreeMap<String, Vec<(String, String)>>;

/// INI files the emulator reads, keyed by the section prefix that selects them.
const FILES: &[(&str, &str)] = &[
    ("user", "configs.user.ini"),
    ("main", "configs.main.ini"),
    ("app", "configs.app.ini"),
    ("overlay", "configs.overlay.ini"),
];

/// A set of emulator settings.
///
/// Entries are keyed by fully-qualified `section::key`, e.g.
/// `user::general::account_name`. Storing them flat keeps merging trivial and lets any
/// setting the emulator supports be expressed without modelling its whole schema.
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
#[serde(transparent)]
pub struct EmuConfig {
    pub entries: BTreeMap<String, String>,
}

impl EmuConfig {
    #[must_use]
    pub fn is_empty(&self) -> bool {
        self.entries.is_empty()
    }

    /// Set one entry. The key must be `<file>::<section>::<key>`, where `<file>` is one
    /// of `user`, `main`, `app` or `overlay`.
    pub fn set(&mut self, key: &str, value: &str) -> Result<()> {
        let (section, _) = split_key(key)?;
        file_for(&section)?;
        self.entries.insert(key.to_owned(), value.to_owned());
        Ok(())
    }

    /// Remove one entry, reporting whether it was present.
    pub fn unset(&mut self, key: &str) -> bool {
        self.entries.remove(key).is_some()
    }

    #[must_use]
    pub fn get(&self, key: &str) -> Option<&str> {
        self.entries.get(key).map(String::as_str)
    }

    /// Combine two layers; entries in `other` win.
    #[must_use]
    pub fn merged_with(&self, other: &Self) -> Self {
        let mut entries = self.entries.clone();
        entries.extend(other.entries.iter().map(|(k, v)| (k.clone(), v.clone())));
        Self { entries }
    }

    /// Render to `(filename, contents)` pairs, one per INI file that has entries.
    #[must_use]
    pub fn render(&self) -> Vec<(String, String)> {
        // file -> section -> [(key, value)]
        let mut by_file: BTreeMap<&str, SectionMap> = BTreeMap::new();

        for (full_key, value) in &self.entries {
            let Ok((section, key)) = split_key(full_key) else {
                continue;
            };
            let Ok(file) = file_for(&section) else {
                continue;
            };
            by_file
                .entry(file)
                .or_default()
                .entry(section)
                .or_default()
                .push((key, value.clone()));
        }

        by_file
            .into_iter()
            .map(|(file, sections)| {
                let mut out = String::from("# generated by Condenser — edits here are overwritten\n");
                for (section, mut pairs) in sections {
                    pairs.sort();
                    let _ = writeln!(out, "\n[{section}]");
                    for (key, value) in pairs {
                        let _ = writeln!(out, "{key}={value}");
                    }
                }
                (file.to_owned(), out)
            })
            .collect()
    }

    /// Write the rendered files into a `steam_settings` directory, removing any
    /// config file that no longer has entries so stale settings cannot linger.
    pub fn write_to(&self, steam_settings: &Path) -> Result<()> {
        std::fs::create_dir_all(steam_settings)?;
        let rendered = self.render();

        for (_, filename) in FILES {
            let path = steam_settings.join(filename);
            match rendered.iter().find(|(name, _)| name == filename) {
                Some((_, contents)) => std::fs::write(&path, contents)?,
                None => {
                    let _ = std::fs::remove_file(&path);
                }
            }
        }
        Ok(())
    }
}

/// Split `user::general::account_name` into (`user::general`, `account_name`).
fn split_key(full_key: &str) -> Result<(String, String)> {
    let (section, key) = full_key
        .rsplit_once("::")
        .ok_or_else(|| Error::BadConfigKey(full_key.to_owned()))?;
    if section.is_empty() || key.is_empty() || !section.contains("::") {
        return Err(Error::BadConfigKey(full_key.to_owned()));
    }
    Ok((section.to_owned(), key.to_owned()))
}

/// Map a section to the INI file that holds it.
fn file_for(section: &str) -> Result<&'static str> {
    let prefix = section.split("::").next().unwrap_or_default();
    FILES
        .iter()
        .find(|(p, _)| *p == prefix)
        .map(|(_, file)| *file)
        .ok_or_else(|| Error::BadConfigKey(section.to_owned()))
}

/// Settings every deployment gets unless overridden.
///
/// `account_name` lives in `configs.user.ini`; the old Goldberg-era
/// `force_account_name.txt` is not read by current `gbe_fork` at all.
#[must_use]
pub fn defaults() -> EmuConfig {
    let mut config = EmuConfig::default();
    let _ = config.set("user::general::account_name", "Condenser");
    let _ = config.set("user::general::language", "english");
    config
}

/// Commonly-used keys, surfaced in the UI and by `condenser config keys`.
pub const COMMON_KEYS: &[(&str, &str)] = &[
    ("user::general::account_name", "Display name reported to the game"),
    ("user::general::account_steamid", "SteamID64 to report (blank = generated)"),
    ("user::general::language", "Game language, e.g. english"),
    ("user::general::ip_country", "Reported country, ISO 3166-1 alpha-2"),
    ("user::saves::saves_folder_name", "Name of the saves folder"),
    ("user::saves::local_save_path", "Portable saves path (ignores global)"),
    ("main::general::disable_lan_only", "Disable LAN-only mode"),
    ("main::general::new_app_ticket", "Use the newer app ticket format"),
    ("main::connectivity::disable_networking", "Disable all networking"),
    ("main::connectivity::listen_port", "UDP/TCP port for LAN discovery"),
    ("main::connectivity::offline", "Report the account as offline"),
    ("main::misc::achievements_bypass", "Report all achievements as unlocked"),
    ("app::general::unlock_all_dlc", "Report every DLC as owned"),
    ("overlay::general::enable_experimental_overlay", "Enable the in-game overlay"),
];

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn key_must_name_a_file_and_section() {
        let mut config = EmuConfig::default();
        assert!(config.set("user::general::account_name", "x").is_ok());
        // Missing section component.
        assert!(config.set("account_name", "x").is_err());
        assert!(config.set("user::account_name", "x").is_err());
        // Unknown file prefix.
        assert!(config.set("bogus::general::key", "x").is_err());
    }

    #[test]
    fn sections_route_to_the_right_ini_file() {
        let mut config = EmuConfig::default();
        config.set("user::general::account_name", "Ada").unwrap();
        config.set("main::connectivity::offline", "1").unwrap();
        config.set("app::general::unlock_all_dlc", "1").unwrap();
        config.set("overlay::general::enable_experimental_overlay", "0").unwrap();

        let rendered = config.render();
        let names: Vec<&str> = rendered.iter().map(|(n, _)| n.as_str()).collect();
        assert!(names.contains(&"configs.user.ini"));
        assert!(names.contains(&"configs.main.ini"));
        assert!(names.contains(&"configs.app.ini"));
        assert!(names.contains(&"configs.overlay.ini"));

        let user = &rendered.iter().find(|(n, _)| n == "configs.user.ini").unwrap().1;
        assert!(user.contains("[user::general]"), "got:\n{user}");
        assert!(user.contains("account_name=Ada"), "got:\n{user}");
    }

    /// Per-game entries must win over global ones, matching upstream precedence.
    #[test]
    fn per_game_overrides_global() {
        let mut global = EmuConfig::default();
        global.set("user::general::account_name", "Global").unwrap();
        global.set("user::general::language", "english").unwrap();

        let mut game = EmuConfig::default();
        game.set("user::general::account_name", "PerGame").unwrap();

        let merged = global.merged_with(&game);
        assert_eq!(merged.get("user::general::account_name"), Some("PerGame"));
        assert_eq!(
            merged.get("user::general::language"),
            Some("english"),
            "global entries without an override must survive"
        );
    }

    #[test]
    fn writing_removes_files_that_no_longer_have_entries() {
        let tmp = tempfile::tempdir().unwrap();
        let dir = tmp.path().join("steam_settings");

        let mut config = EmuConfig::default();
        config.set("user::general::account_name", "Ada").unwrap();
        config.set("main::connectivity::offline", "1").unwrap();
        config.write_to(&dir).unwrap();
        assert!(dir.join("configs.user.ini").exists());
        assert!(dir.join("configs.main.ini").exists());

        // Dropping the main:: entry must delete its file, not leave it stale.
        config.unset("main::connectivity::offline");
        config.write_to(&dir).unwrap();
        assert!(dir.join("configs.user.ini").exists());
        assert!(
            !dir.join("configs.main.ini").exists(),
            "stale config file should have been removed"
        );
    }

    #[test]
    fn defaults_set_the_account_name_where_the_emulator_reads_it() {
        let rendered = defaults().render();
        let (name, contents) = rendered
            .iter()
            .find(|(n, _)| n == "configs.user.ini")
            .expect("defaults should produce a user config");
        assert_eq!(name, "configs.user.ini");
        assert!(contents.contains("account_name=Condenser"));
    }

    #[test]
    fn every_common_key_is_valid() {
        let mut config = EmuConfig::default();
        for (key, _) in COMMON_KEYS {
            assert!(config.set(key, "1").is_ok(), "{key} should be a valid key");
        }
    }
}
